

# default the module name
appName: demo-java-server

service:
  type: ClusterIP
  ports: 
    grpc: 50051

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

cd:
  cluster: local-test

deployment:
  replicas: 2
  image:
    pullPolicy: IfNotPresent
    name: "docker-local.jfrog.io/demo-java-server:latest"
    command: "./application -Dquarkus.http.host=0.0.0.0"
  env:
    APP_ENV: TEST
    LOG_LEVEL: warn


