include:
  - project: 'it-devops/ci'
    #    ref: v1.0.211130
    file:
      - '.gradle.yml'
#      - '.junit.yml'
#      - '.docker.yml'

build:
  extends: .gradle
  variables:
    SONAR_HOST_URL: "http://sonarqube-sonarqube.gitlab:9000"
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
  script:
    #  gradle clean build -x test  -Dquarkus.package.type=native  -Dquarkus.native.additional-build-args=-Ob
    # ci use the GRADLE_OPTS to build native
    - gradle build -x test
    - strings test-server/build/*-runner | grep GraalVM
#    - gradle clean $publish
    - gradle clean publish
    - gradle test sonarqube -Dsonar.qualitygate.wait=true
    - echo 'OK,ignore sonarqube error'

