#image:  "quay.io/quarkus/ubi-quarkus-native-image:21.2-java11"

image: "younglove/graalvm-gradle:7"
stages:
#  - build
#  - test
  - release
#  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#  DOCKER_HOST: tcp://docker:2376
#  DOCKER_TLS_CERTDIR: "/certs"
#
#build:
#  stage: build
#  script:
#    - gradle build -Dquarkus.package.type=native


#
#release-maven:
#  stage: release
#  script:
#    - gradle publish

release-image:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REPO: registry.botaoyx.com/pkg/docker
    DEMO_JAVA_SERVER_TAG: "$REPO/demo-java-server:$CI_COMMIT_REF_SLUG"
    DEMO_JAVA_CLIENT_TAG: "$REPO/demo-java-client:$CI_COMMIT_REF_SLUG"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://$CI_REGISTRY/v2/\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - echo "mytag ->  $DEMO_JAVA_SERVER_TAG"
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/demo-java-server --dockerfile ./Dockerfile --destination $DEMO_JAVA_SERVER_TAG
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/demo-java-client --dockerfile ./Dockerfile --destination $DEMO_JAVA_CLIENT_TAG
#  rules:
#    - if: $CI_COMMIT_TAG

# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes
#release-use-docker:
#  image: docker:19.03.13
#  stage: release-use-docker
#  services:
#    - docker:19.03.13-dind
#  before_script:
#    - docker info
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - pwd && echo " -> begin cd ./demo-java-server"
#    - cd ./demo-java-server && docker build -t $DEMO_JAVA_SERVER_TAG .
#    - pwd && echo " -> begin cd ../demo-java-client"
#    - cd ../demo-java-client && docker build -t $DEMO_JAVA_CLIENT_TAG .
#    - cd .. && pwd
#    - docker push $DEMO_JAVA_SERVER_TAG
#    - docker push $DEMO_JAVA_CLIENT_TAG
#  only:
#    - main
