image: "jcr.botaoyx.com/img/graalvm-gradle:7.21.2"
stages:
#  - build
#  - test
  - release
#  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_MODULES: "demo-java-server demo-java-client"


#build:
#  stage: build
#  script:
#    - gradle build -Dquarkus.package.type=native

#release-maven:
#  stage: release
#  script:
#    - gradle publish

release-image:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
    CONTEXT_PREFIX: "$KANIKO_CACHE_ARGS --dockerfile ./Dockerfile  --context $CI_PROJECT_DIR"
    IMAGE_TAG: "$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHORT_SHA"
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_JCR\":{\"auth\":\"$(echo -n gitlab:${CI_JCR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      for module in ${DOCKER_MODULES}
      do
        /kaniko/executor $CONTEXT_PREFIX/$module --destination $CI_JCR/img/$module:$IMAGE_TAG
      done
#  rules:
#    - if: $CI_COMMIT_TAG

# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes
#release-use-docker:
#  image: docker:19.03.13
#  stage: release-use-docker
#  services:
#    - docker:19.03.13-dind
#  before_script:
#    - docker info
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - pwd && echo " -> begin cd ./demo-java-server"
#    - cd ./demo-java-server && docker build -t $DEMO_JAVA_SERVER_TAG .
#    - pwd && echo " -> begin cd ../demo-java-client"
#    - cd ../demo-java-client && docker build -t $DEMO_JAVA_CLIENT_TAG .
#    - cd .. && pwd
#    - docker push $DEMO_JAVA_SERVER_TAG
#    - docker push $DEMO_JAVA_CLIENT_TAG
#  only:
#    - main
