image: "jcr.botaoyx.com/img/graalvm-gradle:7.21.2"
#stages:
#  .pre
#  build
#  test
#  deploy
#  .post

#before_script:
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - '*/build/'
    - ./*/build/*
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DEPLOY_NS: example
  DOCKER_MODULES: "demo-java-server demo-java-client"
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  script:
    - gradle build
      #-Dquarkus.package.type=native

#deploy-maven:
#  stage: deploy
#  script:
#    - gradle publish

# https://docs.gitlab.com/ee/ci/yaml/index.html#includeremote

deploy-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
#  variables:
#    KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
#    CONTEXT_PREFIX: "$KANIKO_CACHE_ARGS -f ./Dockerfile  --context $CI_PROJECT_DIR"
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_JCR\":{\"auth\":\"$(echo -n gitlab:${CI_JCR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - |
      for module in ${DOCKER_MODULES}
      do
        cd $CI_PROJECT_DIR/$module && pwd && ls -la ./build
        /kaniko/executor --cache  -c $CI_PROJECT_DIR/$module -d $CI_JCR/img/$module:$IMAGE_TAG
      done
#  rules:
#    - if: $CI_COMMIT_TAG
# if src/main/changed


# helm

deploy-helm:
  stage: deploy
  image:
    name: jcr.botaoyx.com/img/helm-kubectl:3.5.3
  script:
    - |
      for module in ${DOCKER_MODULES}
      do
        chart=./$module/src/main/helm
        yq e -i ".name= \"$module\" | .version= \"1.0.$CI_PIPELINE_IID\"" $chart/Chart.yaml
        yq e -i ".appName= \"$module\" | .deployment.image.name = \"$CI_JCR/img/$module:$IMAGE_TAG\""  $chart/values.yaml
        helm template --debug  --dry-run "$chart"
        helm package "$chart"
        curl -H "X-JFrog-Art-Api:$JCR_TOKEN" -T "./${module}-1.0.$CI_PIPELINE_IID.tgz" \
          "https://${CI_JCR}/artifactory/charts/${DEPLOY_NS}/"
      done
#  only:
#    refs:
#      - branches
#    changes:
#      - Dockerfile
#      - docker/scripts/*
#      - dockerfiles/**/*
#  except:
#    - tags


# deploy
# helm repo add charts https://jcr.botaoyx.com/artifactory/api/helm/charts \
#--username <USERNAME> --password <PASSWORD>

