
variables:
  # 多个空格分割
  APP_NAME: "rpcurl"
  APP_NAMESPACE: common

include:
  - project: 'it-devops/ci'
    #    ref: v1.0.211130
    file:
      - '.docker-helm-var.yml'
      - '.gradle.yml'
      - '.docker-java.yml'
      - '.junit.yml'
      - '.helm-java.yml'

build:
  extends: .gradle
  script:
    - gradle build -Dquarkus.package.type=native -x test
    - gradle publish


.docker-helm-var:
  variables:
    DOCKER_TAG: latest


docker:
  extends: .docker-java

.helm:
  extends: .helm-java


# anchors
# reference-tags
# extend

# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags
# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#anchors


#.helm:
#  extends:
#    - .helm-java
#    - .only-changes


# deploy
# helm repo add charts https://jcr.botaoyx.com/artifactory/api/helm/charts \
#--username <USERNAME> --password <PASSWORD>

