
variables:
  APP_NAMES: "rpcurl"
  APP_NAMESPACE: common

include:
  - project: 'it-devops/ci'
    #    ref: v1.0.211130
    file:
      - '.docker-helm-var.yml'
      - '.gradle.yml'
      - '.docker-java.yml'
      - '.junit.yml'
      - '.helm-java.yml'
      - '.changes-java.yml'


#.changes-java:
#  only:
#    changes:
#      - "./*/src/**/*"
#      - "./*/*.properties"
#      - "./*/*.xml"
#      - "./*/*.gradle"
#      - "./*/*.yaml"


build:
  extends: .gradle
  script:
    - gradle build -Dquarkus.package.type=native -x test
    - gradle publish


.docker-helm-var:
  variables:
    APP_VERSION: 1.0.$CI_PIPELINE_ID
    DOCKER_REPO: $CI_JCR/img/$APP_NAMESPACE
    DOCKER_TAG: latest


.docker:
  extends: .docker-java

.helm:
  extends: .helm-java

#.helm:
#  extends:
#    - .helm-java
#    - .only-changes


# deploy
# helm repo add charts https://jcr.botaoyx.com/artifactory/api/helm/charts \
#--username <USERNAME> --password <PASSWORD>

