
variables:
  APP_NAMES: "rpcurl"
  APP_NAMESPACE: common


.docker-helm-var:
  variables:
    APP_VERSION: 1.0.$CI_PIPELINE_ID
    DOCKER_REPO: $CI_JCR/img/$APP_NAMESPACE
    DOCKER_TAG: latest

include:
  - project: 'it-devops/ci'
    ref: v1.0.211130
    file:
      - '.gradle.yml'
      - '.docker-java.yml'
      - '.junit.yml'
      - '.helm-java.yml'
      - '.only-changes.yml'


#.only-changes:
#  only:
#    variables:
#      - $CI_COMMIT_REF_PROTECTED
#    changes:
#      - "./*/src/**/*"

build:
  extends:
    - .gradle
    - .only-changes
  script:
    - gradle build -Dquarkus.package.type=native -x test
    - gradle publish

.docker:
  extends:
    - .docker-java
    - .only-changes

.helm:
  extends:
    - .helm-java
    - .only-changes


# deploy
# helm repo add charts https://jcr.botaoyx.com/artifactory/api/helm/charts \
#--username <USERNAME> --password <PASSWORD>

