//version = '1.0.0'
apply from: "$rootProject.projectDir/gradle/upload.gradle"

java{
    sourceCompatibility = '11'
    targetCompatibility = "11"
}

dependencies {

    // just for Transitive Dependency，most sub project need below two lib.
    api 'jakarta.validation:jakarta.validation-api:3.1.0'
    // just for PageList/PageQuery , in bt-mybatis project.

    compileOnly "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
}
