// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package tech.krpc.internal;

/**
 * Protobuf type {@code tech.krpc.internal.InputProto}
 */
public final class InputProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tech.krpc.internal.InputProto)
        tech.krpc.internal.InputProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InputProto.newBuilder() to construct.
  private InputProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InputProto() {
    e_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new tech.krpc.internal.InputProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InputProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            e_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            dataCase_ = 2;
            data_ = s;
            break;
          }
          case 26: {
            dataCase_ = 3;
            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Internal.internal_static_com_bt_rpc_internal_InputProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Internal.internal_static_com_bt_rpc_internal_InputProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.krpc.internal.InputProto.class, Builder.class);
  }

  private int dataCase_ = 0;
  private Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    UTF8(2),
    BS(3),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return UTF8;
        case 3: return BS;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int E_FIELD_NUMBER = 1;
  private int e_;
  /**
   * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
   * @return The enum numeric value on the wire for e.
   */
  @Override public int getEValue() {
    return e_;
  }
  /**
   * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
   * @return The e.
   */
  @Override public tech.krpc.internal.SerialEnum getE() {
    @SuppressWarnings("deprecation")
    tech.krpc.internal.SerialEnum result = tech.krpc.internal.SerialEnum.valueOf(e_);
    return result == null ? tech.krpc.internal.SerialEnum.UNRECOGNIZED : result;
  }

  public static final int UTF8_FIELD_NUMBER = 2;
  /**
   * <pre>
   *for json , txt like serial
   * </pre>
   *
   * <code>string utf8 = 2;</code>
   * @return Whether the utf8 field is set.
   */
  public boolean hasUtf8() {
    return dataCase_ == 2;
  }
  /**
   * <pre>
   *for json , txt like serial
   * </pre>
   *
   * <code>string utf8 = 2;</code>
   * @return The utf8.
   */
  public String getUtf8() {
    Object ref = "";
    if (dataCase_ == 2) {
      ref = data_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (dataCase_ == 2) {
        data_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *for json , txt like serial
   * </pre>
   *
   * <code>string utf8 = 2;</code>
   * @return The bytes for utf8.
   */
  public com.google.protobuf.ByteString
      getUtf8Bytes() {
    Object ref = "";
    if (dataCase_ == 2) {
      ref = data_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (dataCase_ == 2) {
        data_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BS_FIELD_NUMBER = 3;
  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 3;</code>
   * @return Whether the bs field is set.
   */
  @Override
  public boolean hasBs() {
    return dataCase_ == 3;
  }
  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 3;</code>
   * @return The bs.
   */
  @Override
  public com.google.protobuf.ByteString getBs() {
    if (dataCase_ == 3) {
      return (com.google.protobuf.ByteString) data_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (e_ != tech.krpc.internal.SerialEnum.JSON.getNumber()) {
      output.writeEnum(1, e_);
    }
    if (dataCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
    }
    if (dataCase_ == 3) {
      output.writeBytes(
          3, (com.google.protobuf.ByteString) data_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (e_ != tech.krpc.internal.SerialEnum.JSON.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, e_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            3, (com.google.protobuf.ByteString) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.krpc.internal.InputProto)) {
      return super.equals(obj);
    }
    tech.krpc.internal.InputProto other = (tech.krpc.internal.InputProto) obj;

    if (e_ != other.e_) return false;
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getUtf8()
            .equals(other.getUtf8())) return false;
        break;
      case 3:
        if (!getBs()
            .equals(other.getBs())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + E_FIELD_NUMBER;
    hash = (53 * hash) + e_;
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + UTF8_FIELD_NUMBER;
        hash = (53 * hash) + getUtf8().hashCode();
        break;
      case 3:
        hash = (37 * hash) + BS_FIELD_NUMBER;
        hash = (53 * hash) + getBs().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.krpc.internal.InputProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.krpc.internal.InputProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.krpc.internal.InputProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.krpc.internal.InputProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tech.krpc.internal.InputProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.krpc.internal.InputProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.krpc.internal.InputProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tech.krpc.internal.InputProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tech.krpc.internal.InputProto)
          InputProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Internal.internal_static_com_bt_rpc_internal_InputProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Internal.internal_static_com_bt_rpc_internal_InputProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.krpc.internal.InputProto.class, Builder.class);
    }

    // Construct using tech.krpc.internal.InputProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      e_ = 0;

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Internal.internal_static_com_bt_rpc_internal_InputProto_descriptor;
    }

    @Override
    public tech.krpc.internal.InputProto getDefaultInstanceForType() {
      return tech.krpc.internal.InputProto.getDefaultInstance();
    }

    @Override
    public tech.krpc.internal.InputProto build() {
      tech.krpc.internal.InputProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public tech.krpc.internal.InputProto buildPartial() {
      tech.krpc.internal.InputProto result = new tech.krpc.internal.InputProto(this);
      result.e_ = e_;
      if (dataCase_ == 2) {
        result.data_ = data_;
      }
      if (dataCase_ == 3) {
        result.data_ = data_;
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.krpc.internal.InputProto) {
        return mergeFrom((tech.krpc.internal.InputProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.krpc.internal.InputProto other) {
      if (other == tech.krpc.internal.InputProto.getDefaultInstance()) return this;
      if (other.e_ != 0) {
        setEValue(other.getEValue());
      }
      switch (other.getDataCase()) {
        case UTF8: {
          dataCase_ = 2;
          data_ = other.data_;
          onChanged();
          break;
        }
        case BS: {
          setBs(other.getBs());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tech.krpc.internal.InputProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tech.krpc.internal.InputProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int e_ = 0;
    /**
     * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
     * @return The enum numeric value on the wire for e.
     */
    @Override public int getEValue() {
      return e_;
    }
    /**
     * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
     * @param value The enum numeric value on the wire for e to set.
     * @return This builder for chaining.
     */
    public Builder setEValue(int value) {
      
      e_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
     * @return The e.
     */
    @Override
    public tech.krpc.internal.SerialEnum getE() {
      @SuppressWarnings("deprecation")
      tech.krpc.internal.SerialEnum result = tech.krpc.internal.SerialEnum.valueOf(e_);
      return result == null ? tech.krpc.internal.SerialEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
     * @param value The e to set.
     * @return This builder for chaining.
     */
    public Builder setE(SerialEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      e_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearE() {
      
      e_ = 0;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @return Whether the utf8 field is set.
     */
    @Override
    public boolean hasUtf8() {
      return dataCase_ == 2;
    }
    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @return The utf8.
     */
    @Override
    public String getUtf8() {
      Object ref = "";
      if (dataCase_ == 2) {
        ref = data_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (dataCase_ == 2) {
          data_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @return The bytes for utf8.
     */
    @Override
    public com.google.protobuf.ByteString
        getUtf8Bytes() {
      Object ref = "";
      if (dataCase_ == 2) {
        ref = data_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (dataCase_ == 2) {
          data_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @param value The utf8 to set.
     * @return This builder for chaining.
     */
    public Builder setUtf8(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 2;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtf8() {
      if (dataCase_ == 2) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *for json , txt like serial
     * </pre>
     *
     * <code>string utf8 = 2;</code>
     * @param value The bytes for utf8 to set.
     * @return This builder for chaining.
     */
    public Builder setUtf8Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataCase_ = 2;
      data_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * ByteString, others Serialization transfer by protobuf
     * </pre>
     *
     * <code>bytes bs = 3;</code>
     * @return Whether the bs field is set.
     */
    public boolean hasBs() {
      return dataCase_ == 3;
    }
    /**
     * <pre>
     * ByteString, others Serialization transfer by protobuf
     * </pre>
     *
     * <code>bytes bs = 3;</code>
     * @return The bs.
     */
    public com.google.protobuf.ByteString getBs() {
      if (dataCase_ == 3) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * ByteString, others Serialization transfer by protobuf
     * </pre>
     *
     * <code>bytes bs = 3;</code>
     * @param value The bs to set.
     * @return This builder for chaining.
     */
    public Builder setBs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 3;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ByteString, others Serialization transfer by protobuf
     * </pre>
     *
     * <code>bytes bs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBs() {
      if (dataCase_ == 3) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tech.krpc.internal.InputProto)
  }

  // @@protoc_insertion_point(class_scope:tech.krpc.internal.InputProto)
  private static final tech.krpc.internal.InputProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.krpc.internal.InputProto();
  }

  public static tech.krpc.internal.InputProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<tech.krpc.internal.InputProto>
      PARSER = new com.google.protobuf.AbstractParser<tech.krpc.internal.InputProto>() {
    @Override
    public tech.krpc.internal.InputProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new tech.krpc.internal.InputProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<tech.krpc.internal.InputProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<tech.krpc.internal.InputProto> getParserForType() {
    return PARSER;
  }

  @Override
  public tech.krpc.internal.InputProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

