// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: internal.proto

#include "internal.pb.h"
#include "internal.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace krpc {

static const char* KrpcBaseService_method_names[] = {
  "/krpc.KrpcBaseService/callUnary",
};

std::unique_ptr< KrpcBaseService::Stub> KrpcBaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KrpcBaseService::Stub> stub(new KrpcBaseService::Stub(channel, options));
  return stub;
}

KrpcBaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_callUnary_(KrpcBaseService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KrpcBaseService::Stub::callUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::krpc::OutputProto* response) {
  return ::grpc::internal::BlockingUnaryCall< ::krpc::InputProto, ::krpc::OutputProto, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_callUnary_, context, request, response);
}

void KrpcBaseService::Stub::async::callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::krpc::InputProto, ::krpc::OutputProto, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_callUnary_, context, request, response, std::move(f));
}

void KrpcBaseService::Stub::async::callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_callUnary_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>* KrpcBaseService::Stub::PrepareAsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::krpc::OutputProto, ::krpc::InputProto, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_callUnary_, context, request);
}

::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>* KrpcBaseService::Stub::AsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccallUnaryRaw(context, request, cq);
  result->StartCall();
  return result;
}

KrpcBaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KrpcBaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KrpcBaseService::Service, ::krpc::InputProto, ::krpc::OutputProto, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KrpcBaseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::krpc::InputProto* req,
             ::krpc::OutputProto* resp) {
               return service->callUnary(ctx, req, resp);
             }, this)));
}

KrpcBaseService::Service::~Service() {
}

::grpc::Status KrpcBaseService::Service::callUnary(::grpc::ServerContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace krpc

