// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: internal.proto
// Protobuf C++ Version: 6.30.0

#include "internal.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace krpc {

inline constexpr OutputProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        code_{0},
        data_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR OutputProto::OutputProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OutputProto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OutputProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OutputProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutputProtoDefaultTypeInternal() {}
  union {
    OutputProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutputProtoDefaultTypeInternal _OutputProto_default_instance_;

inline constexpr InputProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        utf8_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR InputProto::InputProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(InputProto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InputProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InputProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InputProtoDefaultTypeInternal() {}
  union {
    InputProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InputProtoDefaultTypeInternal _InputProto_default_instance_;
}  // namespace krpc
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_internal_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_internal_2eproto = nullptr;
const ::uint32_t
    TableStruct_internal_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::krpc::InputProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::krpc::InputProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::krpc::InputProto, _impl_.utf8_),
        0,
        PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _impl_.code_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _impl_.data_),
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::krpc::InputProto)},
        {10, 22, -1, sizeof(::krpc::OutputProto)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::krpc::_InputProto_default_instance_._instance,
    &::krpc::_OutputProto_default_instance_._instance,
};
const char descriptor_table_protodef_internal_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016internal.proto\022\004krpc\"\032\n\nInputProto\022\014\n\004"
    "utf8\030\002 \001(\t\"B\n\013OutputProto\022\014\n\004code\030\001 \001(\005\022"
    "\r\n\003msg\030\002 \001(\tH\000\022\016\n\004utf8\030\003 \001(\tH\000B\006\n\004data2C"
    "\n\017KrpcBaseService\0220\n\tcallUnary\022\020.krpc.In"
    "putProto\032\021.krpc.OutputProtob\006proto3"
};
static ::absl::once_flag descriptor_table_internal_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_internal_2eproto = {
    false,
    false,
    195,
    descriptor_table_protodef_internal_2eproto,
    "internal.proto",
    &descriptor_table_internal_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_internal_2eproto::offsets,
    file_level_enum_descriptors_internal_2eproto,
    file_level_service_descriptors_internal_2eproto,
};
namespace krpc {
// ===================================================================

class InputProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<InputProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InputProto, _impl_._has_bits_);
};

InputProto::InputProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InputProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:krpc.InputProto)
}
PROTOBUF_NDEBUG_INLINE InputProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::krpc::InputProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        utf8_(arena, from.utf8_) {}

InputProto::InputProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const InputProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InputProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InputProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:krpc.InputProto)
}
PROTOBUF_NDEBUG_INLINE InputProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        utf8_(arena) {}

inline void InputProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InputProto::~InputProto() {
  // @@protoc_insertion_point(destructor:krpc.InputProto)
  SharedDtor(*this);
}
inline void InputProto::SharedDtor(MessageLite& self) {
  InputProto& this_ = static_cast<InputProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.utf8_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL InputProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) InputProto(arena);
}
constexpr auto InputProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(InputProto),
                                            alignof(InputProto));
}
constexpr auto InputProto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_InputProto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &InputProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<InputProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &InputProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<InputProto>(), &InputProto::ByteSizeLong,
              &InputProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(InputProto, _impl_._cached_size_),
          false,
      },
      &InputProto::kDescriptorMethods,
      &descriptor_table_internal_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        InputProto_class_data_ =
            InputProto::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL InputProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&InputProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(InputProto_class_data_.tc_table);
  return InputProto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2>
InputProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InputProto, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    InputProto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::krpc::InputProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string utf8 = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(InputProto, _impl_.utf8_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string utf8 = 2;
    {PROTOBUF_FIELD_OFFSET(InputProto, _impl_.utf8_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\4\0\0\0\0\0\0"
    "krpc.InputProto"
    "utf8"
  }},
};
PROTOBUF_NOINLINE void InputProto::Clear() {
// @@protoc_insertion_point(message_clear_start:krpc.InputProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.utf8_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL InputProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const InputProto& this_ = static_cast<const InputProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL InputProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const InputProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:krpc.InputProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string utf8 = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_utf8().empty()) {
      const std::string& _s = this_._internal_utf8();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "krpc.InputProto.utf8");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:krpc.InputProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InputProto::ByteSizeLong(const MessageLite& base) {
  const InputProto& this_ = static_cast<const InputProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InputProto::ByteSizeLong() const {
  const InputProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:krpc.InputProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string utf8 = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_utf8().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_utf8());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void InputProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InputProto*>(&to_msg);
  auto& from = static_cast<const InputProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:krpc.InputProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_utf8().empty()) {
      _this->_internal_set_utf8(from._internal_utf8());
    } else {
      if (_this->_impl_.utf8_.IsDefault()) {
        _this->_internal_set_utf8("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InputProto::CopyFrom(const InputProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:krpc.InputProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InputProto::InternalSwap(InputProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.utf8_, &other->_impl_.utf8_, arena);
}

::google::protobuf::Metadata InputProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OutputProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<OutputProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OutputProto, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::krpc::OutputProto, _impl_._oneof_case_);
};

OutputProto::OutputProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OutputProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:krpc.OutputProto)
}
PROTOBUF_NDEBUG_INLINE OutputProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::krpc::OutputProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_{},
        _oneof_case_{from._oneof_case_[0]} {}

OutputProto::OutputProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OutputProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OutputProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OutputProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;
  switch (data_case()) {
    case DATA_NOT_SET:
      break;
      case kMsg:
        new (&_impl_.data_.msg_) decltype(_impl_.data_.msg_){arena, from._impl_.data_.msg_};
        break;
      case kUtf8:
        new (&_impl_.data_.utf8_) decltype(_impl_.data_.utf8_){arena, from._impl_.data_.utf8_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:krpc.OutputProto)
}
PROTOBUF_NDEBUG_INLINE OutputProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_{},
        _oneof_case_{} {}

inline void OutputProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
OutputProto::~OutputProto() {
  // @@protoc_insertion_point(destructor:krpc.OutputProto)
  SharedDtor(*this);
}
inline void OutputProto::SharedDtor(MessageLite& self) {
  OutputProto& this_ = static_cast<OutputProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_data()) {
    this_.clear_data();
  }
  this_._impl_.~Impl_();
}

void OutputProto::clear_data() {
// @@protoc_insertion_point(one_of_clear_start:krpc.OutputProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (data_case()) {
    case kMsg: {
      _impl_.data_.msg_.Destroy();
      break;
    }
    case kUtf8: {
      _impl_.data_.utf8_.Destroy();
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}


inline void* PROTOBUF_NONNULL OutputProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OutputProto(arena);
}
constexpr auto OutputProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OutputProto),
                                            alignof(OutputProto));
}
constexpr auto OutputProto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OutputProto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OutputProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OutputProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OutputProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OutputProto>(), &OutputProto::ByteSizeLong,
              &OutputProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OutputProto, _impl_._cached_size_),
          false,
      },
      &OutputProto::kDescriptorMethods,
      &descriptor_table_internal_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        OutputProto_class_data_ =
            OutputProto::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL OutputProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OutputProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OutputProto_class_data_.tc_table);
  return OutputProto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 0, 32, 2>
OutputProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OutputProto, _impl_._has_bits_),
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OutputProto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::krpc::OutputProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OutputProto, _impl_.code_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(OutputProto, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(OutputProto, _impl_.code_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(OutputProto, _impl_.data_.msg_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string utf8 = 3;
    {PROTOBUF_FIELD_OFFSET(OutputProto, _impl_.data_.utf8_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\3\4\0\0\0\0"
    "krpc.OutputProto"
    "msg"
    "utf8"
  }},
};
PROTOBUF_NOINLINE void OutputProto::Clear() {
// @@protoc_insertion_point(message_clear_start:krpc.OutputProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_ = 0;
  clear_data();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OutputProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OutputProto& this_ = static_cast<const OutputProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OutputProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OutputProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:krpc.OutputProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 code = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_code() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_code(), target);
    }
  }

  switch (this_.data_case()) {
    case kMsg: {
      const std::string& _s = this_._internal_msg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "krpc.OutputProto.msg");
      target = stream->WriteStringMaybeAliased(2, _s, target);
      break;
    }
    case kUtf8: {
      const std::string& _s = this_._internal_utf8();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "krpc.OutputProto.utf8");
      target = stream->WriteStringMaybeAliased(3, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:krpc.OutputProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OutputProto::ByteSizeLong(const MessageLite& base) {
  const OutputProto& this_ = static_cast<const OutputProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OutputProto::ByteSizeLong() const {
  const OutputProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:krpc.OutputProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 code = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_code() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_code());
      }
    }
  }
  switch (this_.data_case()) {
    // string msg = 2;
    case kMsg: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_msg());
      break;
    }
    // string utf8 = 3;
    case kUtf8: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_utf8());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OutputProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OutputProto*>(&to_msg);
  auto& from = static_cast<const OutputProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:krpc.OutputProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_code() != 0) {
      _this->_impl_.code_ = from._impl_.code_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_data();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kMsg: {
        if (oneof_needs_init) {
          _this->_impl_.data_.msg_.InitDefault();
        }
        _this->_impl_.data_.msg_.Set(from._internal_msg(), arena);
        break;
      }
      case kUtf8: {
        if (oneof_needs_init) {
          _this->_impl_.data_.utf8_.InitDefault();
        }
        _this->_impl_.data_.utf8_.Set(from._internal_utf8(), arena);
        break;
      }
      case DATA_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OutputProto::CopyFrom(const OutputProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:krpc.OutputProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OutputProto::InternalSwap(OutputProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.code_, other->_impl_.code_);
  swap(_impl_.data_, other->_impl_.data_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata OutputProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace krpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_internal_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
