// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: internal.proto
#ifndef GRPC_internal_2eproto__INCLUDED
#define GRPC_internal_2eproto__INCLUDED

#include "internal.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace krpc {

class KrpcBaseService final {
 public:
  static constexpr char const* service_full_name() {
    return "krpc.KrpcBaseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status callUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::krpc::OutputProto* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>> AsynccallUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>>(AsynccallUnaryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>> PrepareAsynccallUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>>(PrepareAsynccallUnaryRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, std::function<void(::grpc::Status)>) = 0;
      virtual void callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>* AsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::krpc::OutputProto>* PrepareAsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status callUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::krpc::OutputProto* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>> AsynccallUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>>(AsynccallUnaryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>> PrepareAsynccallUnary(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>>(PrepareAsynccallUnaryRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, std::function<void(::grpc::Status)>) override;
      void callUnary(::grpc::ClientContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>* AsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::krpc::OutputProto>* PrepareAsynccallUnaryRaw(::grpc::ClientContext* context, const ::krpc::InputProto& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_callUnary_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status callUnary(::grpc::ServerContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_callUnary() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcallUnary(::grpc::ServerContext* context, ::krpc::InputProto* request, ::grpc::ServerAsyncResponseWriter< ::krpc::OutputProto>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_callUnary<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_callUnary() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::krpc::InputProto, ::krpc::OutputProto>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::krpc::InputProto* request, ::krpc::OutputProto* response) { return this->callUnary(context, request, response); }));}
    void SetMessageAllocatorFor_callUnary(
        ::grpc::MessageAllocator< ::krpc::InputProto, ::krpc::OutputProto>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::krpc::InputProto, ::krpc::OutputProto>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* callUnary(
      ::grpc::CallbackServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_callUnary<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_callUnary() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_callUnary() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcallUnary(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_callUnary() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->callUnary(context, request, response); }));
    }
    ~WithRawCallbackMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* callUnary(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_callUnary : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_callUnary() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::krpc::InputProto, ::krpc::OutputProto>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::krpc::InputProto, ::krpc::OutputProto>* streamer) {
                       return this->StreamedcallUnary(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_callUnary() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status callUnary(::grpc::ServerContext* /*context*/, const ::krpc::InputProto* /*request*/, ::krpc::OutputProto* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcallUnary(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::krpc::InputProto,::krpc::OutputProto>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_callUnary<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_callUnary<Service > StreamedService;
};

}  // namespace krpc


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_internal_2eproto__INCLUDED
