# use this template
# https://gitlab.btrpc.com/it-devops/ci/-/blob/master/helm/java.1.0/values.yaml


extSecret: example-db-secret

deployment:
  corsAllow: course.btrpc.com
  env:
    APP_ENV: TEST
    LOG_LEVEL: warn
    QUARKUS_DATASOURCE_JDBC_URL: "jdbc:mysql://mysql-primary.infra/example"