name: rpcurl
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=3.0.0 <5.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
dependencies: 
  args: ^2.3.0
  btrpc:
    path: ./rpc-dart-client
#    git:
#      url: https://gitlab.zhulinkeji.com/middleware/rpc-dart-client.git
#      ref: 1.0.0
#      url: git@github.com:martin2038/rpc-dart-client.git
      #ref: master
