// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package tech.krpc.internal;

public interface InputProtoOrBuilder
    //    extends
    //// @@protoc_insertion_point(interface_extends:tech.krpc.internal.InputProto)
    //com.google.protobuf.MessageOrBuilder
{

  /**
   * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
   * @return The enum numeric value on the wire for e.
   */
  int getEValue();
  /**
   * <code>.tech.krpc.internal.SerialEnum e = 1;</code>
   * @return The e.
   */
  SerialEnum getE();

  /**
   * <pre>
   *for json , txt like serial
   * </pre>
   *
   * <code>string utf8 = 2;</code>
   * @return Whether the utf8 field is set.
   */
  boolean hasUtf8();
  /**
   * <pre>
   *for json , txt like serial
   * </pre>
   *
   * <code>string utf8 = 2;</code>
   * @return The utf8.
   */
  String getUtf8();
  ///**
  // * <pre>
  // *for json , txt like serial
  // * </pre>
  // *
  // * <code>string utf8 = 2;</code>
  // * @return The bytes for utf8.
  // */
  //com.google.protobuf.ByteString
  //    getUtf8Bytes();

  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 3;</code>
   * @return Whether the bs field is set.
   */
  boolean hasBs();
  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 3;</code>
   * @return The bs.
   */
  byte[] getBs();

  public InputProto.DataCase getDataCase();

  interface InBuilder{
    InBuilder setE(SerialEnum value);
    InBuilder setUtf8(String value);
    InBuilder setBs(byte[] value);
  }
}
