/**
* GENERATED BY BTYX RPC GEN - LESS MODIFY BY HAND
* ${app}.ts  ${.now?iso_local}
*/

import {RpcResult,RpcService,Headers} from '@btyx/rpc';

import {
  IsInt,
  Length,
  IsEmail,
  IsFQDN,
  IsDate,
  Min,
  Max,
  IsOptional,
  IsDefined,
  IsNotEmpty,
  MinLength,
  MaxLength,
  IsPositive,
  IsNegative,
} from 'class-validator';

export const APP = '${app}';

<#list dtos as dto>
export ${dto.input?then('class','interface')}  ${dto.typeName} {
 <#assign hasRequired = false>
 <#list dto.fields?filter(f->! f.hidden) as f>

    <#list (f.annotations![])?filter(a->a.name?has_content) as anno>
    ${anno.name}
    </#list>
    ${f.name}${(dto.input && !f.required)?then('?','')}: ${f.type};
    <#if f.required>
    <#assign hasRequired = true >
    </#if>
 </#list>
 <#if hasRequired>

	constructor(<#list dto.fields?filter(f->f.required) as f>${f.name}: ${f.type}${f?has_next?then(',','')}</#list>) {
		<#list dto.fields?filter(f->f.required) as f>
		this.${f.name} = ${f.name};
		</#list>
	}
 </#if>
}

</#list>
