// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

/**
 * Protobuf type {@code com.bt.rpc.internal.InputMessage}
 */
public final class InputMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bt.rpc.internal.InputMessage)
    InputMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InputMessage.newBuilder() to construct.
  private InputMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InputMessage() {
    se_ = 0;
    b_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InputMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InputMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            se_ = rawValue;
            break;
          }
          case 18: {

            b_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_InputMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_InputMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bt.rpc.internal.InputMessage.class, com.bt.rpc.internal.InputMessage.Builder.class);
  }

  public static final int SE_FIELD_NUMBER = 1;
  private int se_;
  /**
   * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
   * @return The enum numeric value on the wire for se.
   */
  @java.lang.Override public int getSeValue() {
    return se_;
  }
  /**
   * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
   * @return The se.
   */
  @java.lang.Override public com.bt.rpc.internal.SerEnum getSe() {
    @SuppressWarnings("deprecation")
    com.bt.rpc.internal.SerEnum result = com.bt.rpc.internal.SerEnum.valueOf(se_);
    return result == null ? com.bt.rpc.internal.SerEnum.UNRECOGNIZED : result;
  }

  public static final int B_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString b_;
  /**
   * <code>bytes b = 2;</code>
   * @return The b.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getB() {
    return b_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (se_ != com.bt.rpc.internal.SerEnum.NONE.getNumber()) {
      output.writeEnum(1, se_);
    }
    if (!b_.isEmpty()) {
      output.writeBytes(2, b_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (se_ != com.bt.rpc.internal.SerEnum.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, se_);
    }
    if (!b_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, b_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bt.rpc.internal.InputMessage)) {
      return super.equals(obj);
    }
    com.bt.rpc.internal.InputMessage other = (com.bt.rpc.internal.InputMessage) obj;

    if (se_ != other.se_) return false;
    if (!getB()
        .equals(other.getB())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SE_FIELD_NUMBER;
    hash = (53 * hash) + se_;
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + getB().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bt.rpc.internal.InputMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bt.rpc.internal.InputMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.InputMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.InputMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bt.rpc.internal.InputMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bt.rpc.internal.InputMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bt.rpc.internal.InputMessage)
      com.bt.rpc.internal.InputMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_InputMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_InputMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bt.rpc.internal.InputMessage.class, com.bt.rpc.internal.InputMessage.Builder.class);
    }

    // Construct using com.bt.rpc.internal.InputMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      se_ = 0;

      b_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_InputMessage_descriptor;
    }

    @java.lang.Override
    public com.bt.rpc.internal.InputMessage getDefaultInstanceForType() {
      return com.bt.rpc.internal.InputMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.bt.rpc.internal.InputMessage build() {
      com.bt.rpc.internal.InputMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bt.rpc.internal.InputMessage buildPartial() {
      com.bt.rpc.internal.InputMessage result = new com.bt.rpc.internal.InputMessage(this);
      result.se_ = se_;
      result.b_ = b_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bt.rpc.internal.InputMessage) {
        return mergeFrom((com.bt.rpc.internal.InputMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bt.rpc.internal.InputMessage other) {
      if (other == com.bt.rpc.internal.InputMessage.getDefaultInstance()) return this;
      if (other.se_ != 0) {
        setSeValue(other.getSeValue());
      }
      if (other.getB() != com.google.protobuf.ByteString.EMPTY) {
        setB(other.getB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bt.rpc.internal.InputMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bt.rpc.internal.InputMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int se_ = 0;
    /**
     * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
     * @return The enum numeric value on the wire for se.
     */
    @java.lang.Override public int getSeValue() {
      return se_;
    }
    /**
     * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
     * @param value The enum numeric value on the wire for se to set.
     * @return This builder for chaining.
     */
    public Builder setSeValue(int value) {
      
      se_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
     * @return The se.
     */
    @java.lang.Override
    public com.bt.rpc.internal.SerEnum getSe() {
      @SuppressWarnings("deprecation")
      com.bt.rpc.internal.SerEnum result = com.bt.rpc.internal.SerEnum.valueOf(se_);
      return result == null ? com.bt.rpc.internal.SerEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
     * @param value The se to set.
     * @return This builder for chaining.
     */
    public Builder setSe(com.bt.rpc.internal.SerEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      se_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSe() {
      
      se_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString b_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getB() {
      return b_;
    }
    /**
     * <code>bytes b = 2;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes b = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      
      b_ = getDefaultInstance().getB();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bt.rpc.internal.InputMessage)
  }

  // @@protoc_insertion_point(class_scope:com.bt.rpc.internal.InputMessage)
  private static final com.bt.rpc.internal.InputMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bt.rpc.internal.InputMessage();
  }

  public static com.bt.rpc.internal.InputMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InputMessage>
      PARSER = new com.google.protobuf.AbstractParser<InputMessage>() {
    @java.lang.Override
    public InputMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InputMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InputMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InputMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bt.rpc.internal.InputMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

