// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

public interface InputMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bt.rpc.internal.InputMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
   * @return The enum numeric value on the wire for se.
   */
  int getSeValue();
  /**
   * <code>.com.bt.rpc.internal.SerEnum se = 1;</code>
   * @return The se.
   */
  com.bt.rpc.internal.SerEnum getSe();

  /**
   * <code>bytes b = 2;</code>
   * @return The b.
   */
  com.google.protobuf.ByteString getB();
}
