// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

public interface InputProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bt.rpc.internal.InputProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *SerEnum se = 1;
   * </pre>
   *
   * <code>string json = 1;</code>
   * @return The json.
   */
  String getJson();
  /**
   * <pre>
   *SerEnum se = 1;
   * </pre>
   *
   * <code>string json = 1;</code>
   * @return The bytes for json.
   */
  com.google.protobuf.ByteString
      getJsonBytes();
}
