// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

public interface OutputProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bt.rpc.internal.OutputProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
   * </pre>
   *
   * <code>int32 c = 1;</code>
   * @return The c.
   */
  int getC();

  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The m.
   */
  String getM();
  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The bytes for m.
   */
  com.google.protobuf.ByteString
      getMBytes();

  /**
   * <pre>
   *for json
   * </pre>
   *
   * <code>string json = 3;</code>
   * @return Whether the json field is set.
   */
  boolean hasJson();
  /**
   * <pre>
   *for json
   * </pre>
   *
   * <code>string json = 3;</code>
   * @return The json.
   */
  String getJson();
  /**
   * <pre>
   *for json
   * </pre>
   *
   * <code>string json = 3;</code>
   * @return The bytes for json.
   */
  com.google.protobuf.ByteString
      getJsonBytes();

  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 4;</code>
   * @return Whether the bs field is set.
   */
  boolean hasBs();
  /**
   * <pre>
   * ByteString, others Serialization transfer by protobuf
   * </pre>
   *
   * <code>bytes bs = 4;</code>
   * @return The bs.
   */
  com.google.protobuf.ByteString getBs();

  public OutputProto.DataCase getDataCase();
}
