// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

public interface OutputMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bt.rpc.internal.OutputMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
   * </pre>
   *
   * <code>int32 c = 1;</code>
   * @return The c.
   */
  int getC();

  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The m.
   */
  java.lang.String getM();
  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The bytes for m.
   */
  com.google.protobuf.ByteString
      getMBytes();

  /**
   * <pre>
   * Serialization that support both java and c# , and code first , without IDL/proto file
   * </pre>
   *
   * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
   * @return The enum numeric value on the wire for se.
   */
  int getSeValue();
  /**
   * <pre>
   * Serialization that support both java and c# , and code first , without IDL/proto file
   * </pre>
   *
   * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
   * @return The se.
   */
  com.bt.rpc.internal.SerEnum getSe();

  /**
   * <code>string s = 4;</code>
   * @return Whether the s field is set.
   */
  boolean hasS();
  /**
   * <code>string s = 4;</code>
   * @return The s.
   */
  java.lang.String getS();
  /**
   * <code>string s = 4;</code>
   * @return The bytes for s.
   */
  com.google.protobuf.ByteString
      getSBytes();

  /**
   * <code>bytes b = 5;</code>
   * @return Whether the b field is set.
   */
  boolean hasB();
  /**
   * <code>bytes b = 5;</code>
   * @return The b.
   */
  com.google.protobuf.ByteString getB();

  public com.bt.rpc.internal.OutputMessage.PCase getPCase();
}
