// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

/**
 * Protobuf type {@code com.bt.rpc.internal.OutputMessage}
 */
public final class OutputMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bt.rpc.internal.OutputMessage)
    OutputMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutputMessage.newBuilder() to construct.
  private OutputMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutputMessage() {
    m_ = "";
    se_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OutputMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutputMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            c_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            m_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            se_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            pCase_ = 4;
            p_ = s;
            break;
          }
          case 42: {
            pCase_ = 5;
            p_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_OutputMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_OutputMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bt.rpc.internal.OutputMessage.class, com.bt.rpc.internal.OutputMessage.Builder.class);
  }

  private int pCase_ = 0;
  private java.lang.Object p_;
  public enum PCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    S(4),
    B(5),
    P_NOT_SET(0);
    private final int value;
    private PCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PCase valueOf(int value) {
      return forNumber(value);
    }

    public static PCase forNumber(int value) {
      switch (value) {
        case 4: return S;
        case 5: return B;
        case 0: return P_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PCase
  getPCase() {
    return PCase.forNumber(
        pCase_);
  }

  public static final int C_FIELD_NUMBER = 1;
  private int c_;
  /**
   * <pre>
   *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
   * </pre>
   *
   * <code>int32 c = 1;</code>
   * @return The c.
   */
  @java.lang.Override
  public int getC() {
    return c_;
  }

  public static final int M_FIELD_NUMBER = 2;
  private volatile java.lang.Object m_;
  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The m.
   */
  @java.lang.Override
  public java.lang.String getM() {
    java.lang.Object ref = m_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      m_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *detail  message if there is a error ,otherwise  null 
   * </pre>
   *
   * <code>string m = 2;</code>
   * @return The bytes for m.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMBytes() {
    java.lang.Object ref = m_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      m_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SE_FIELD_NUMBER = 3;
  private int se_;
  /**
   * <pre>
   * Serialization that support both java and c# , and code first , without IDL/proto file
   * </pre>
   *
   * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
   * @return The enum numeric value on the wire for se.
   */
  @java.lang.Override public int getSeValue() {
    return se_;
  }
  /**
   * <pre>
   * Serialization that support both java and c# , and code first , without IDL/proto file
   * </pre>
   *
   * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
   * @return The se.
   */
  @java.lang.Override public com.bt.rpc.internal.SerEnum getSe() {
    @SuppressWarnings("deprecation")
    com.bt.rpc.internal.SerEnum result = com.bt.rpc.internal.SerEnum.valueOf(se_);
    return result == null ? com.bt.rpc.internal.SerEnum.UNRECOGNIZED : result;
  }

  public static final int S_FIELD_NUMBER = 4;
  /**
   * <code>string s = 4;</code>
   * @return Whether the s field is set.
   */
  public boolean hasS() {
    return pCase_ == 4;
  }
  /**
   * <code>string s = 4;</code>
   * @return The s.
   */
  public java.lang.String getS() {
    java.lang.Object ref = "";
    if (pCase_ == 4) {
      ref = p_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (pCase_ == 4) {
        p_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string s = 4;</code>
   * @return The bytes for s.
   */
  public com.google.protobuf.ByteString
      getSBytes() {
    java.lang.Object ref = "";
    if (pCase_ == 4) {
      ref = p_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (pCase_ == 4) {
        p_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int B_FIELD_NUMBER = 5;
  /**
   * <code>bytes b = 5;</code>
   * @return Whether the b field is set.
   */
  @java.lang.Override
  public boolean hasB() {
    return pCase_ == 5;
  }
  /**
   * <code>bytes b = 5;</code>
   * @return The b.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getB() {
    if (pCase_ == 5) {
      return (com.google.protobuf.ByteString) p_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (c_ != 0) {
      output.writeInt32(1, c_);
    }
    if (!getMBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, m_);
    }
    if (se_ != com.bt.rpc.internal.SerEnum.NONE.getNumber()) {
      output.writeEnum(3, se_);
    }
    if (pCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, p_);
    }
    if (pCase_ == 5) {
      output.writeBytes(
          5, (com.google.protobuf.ByteString) p_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (c_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, c_);
    }
    if (!getMBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, m_);
    }
    if (se_ != com.bt.rpc.internal.SerEnum.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, se_);
    }
    if (pCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, p_);
    }
    if (pCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            5, (com.google.protobuf.ByteString) p_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bt.rpc.internal.OutputMessage)) {
      return super.equals(obj);
    }
    com.bt.rpc.internal.OutputMessage other = (com.bt.rpc.internal.OutputMessage) obj;

    if (getC()
        != other.getC()) return false;
    if (!getM()
        .equals(other.getM())) return false;
    if (se_ != other.se_) return false;
    if (!getPCase().equals(other.getPCase())) return false;
    switch (pCase_) {
      case 4:
        if (!getS()
            .equals(other.getS())) return false;
        break;
      case 5:
        if (!getB()
            .equals(other.getB())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + C_FIELD_NUMBER;
    hash = (53 * hash) + getC();
    hash = (37 * hash) + M_FIELD_NUMBER;
    hash = (53 * hash) + getM().hashCode();
    hash = (37 * hash) + SE_FIELD_NUMBER;
    hash = (53 * hash) + se_;
    switch (pCase_) {
      case 4:
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getS().hashCode();
        break;
      case 5:
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bt.rpc.internal.OutputMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bt.rpc.internal.OutputMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.OutputMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bt.rpc.internal.OutputMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bt.rpc.internal.OutputMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bt.rpc.internal.OutputMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bt.rpc.internal.OutputMessage)
      com.bt.rpc.internal.OutputMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_OutputMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_OutputMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bt.rpc.internal.OutputMessage.class, com.bt.rpc.internal.OutputMessage.Builder.class);
    }

    // Construct using com.bt.rpc.internal.OutputMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      c_ = 0;

      m_ = "";

      se_ = 0;

      pCase_ = 0;
      p_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bt.rpc.internal.Internal.internal_static_com_bt_rpc_internal_OutputMessage_descriptor;
    }

    @java.lang.Override
    public com.bt.rpc.internal.OutputMessage getDefaultInstanceForType() {
      return com.bt.rpc.internal.OutputMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.bt.rpc.internal.OutputMessage build() {
      com.bt.rpc.internal.OutputMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bt.rpc.internal.OutputMessage buildPartial() {
      com.bt.rpc.internal.OutputMessage result = new com.bt.rpc.internal.OutputMessage(this);
      result.c_ = c_;
      result.m_ = m_;
      result.se_ = se_;
      if (pCase_ == 4) {
        result.p_ = p_;
      }
      if (pCase_ == 5) {
        result.p_ = p_;
      }
      result.pCase_ = pCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bt.rpc.internal.OutputMessage) {
        return mergeFrom((com.bt.rpc.internal.OutputMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bt.rpc.internal.OutputMessage other) {
      if (other == com.bt.rpc.internal.OutputMessage.getDefaultInstance()) return this;
      if (other.getC() != 0) {
        setC(other.getC());
      }
      if (!other.getM().isEmpty()) {
        m_ = other.m_;
        onChanged();
      }
      if (other.se_ != 0) {
        setSeValue(other.getSeValue());
      }
      switch (other.getPCase()) {
        case S: {
          pCase_ = 4;
          p_ = other.p_;
          onChanged();
          break;
        }
        case B: {
          setB(other.getB());
          break;
        }
        case P_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bt.rpc.internal.OutputMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bt.rpc.internal.OutputMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int pCase_ = 0;
    private java.lang.Object p_;
    public PCase
        getPCase() {
      return PCase.forNumber(
          pCase_);
    }

    public Builder clearP() {
      pCase_ = 0;
      p_ = null;
      onChanged();
      return this;
    }


    private int c_ ;
    /**
     * <pre>
     *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
     * </pre>
     *
     * <code>int32 c = 1;</code>
     * @return The c.
     */
    @java.lang.Override
    public int getC() {
      return c_;
    }
    /**
     * <pre>
     *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
     * </pre>
     *
     * <code>int32 c = 1;</code>
     * @param value The c to set.
     * @return This builder for chaining.
     */
    public Builder setC(int value) {
      
      c_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *google.rpc.Code  see https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
     * </pre>
     *
     * <code>int32 c = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearC() {
      
      c_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object m_ = "";
    /**
     * <pre>
     *detail  message if there is a error ,otherwise  null 
     * </pre>
     *
     * <code>string m = 2;</code>
     * @return The m.
     */
    public java.lang.String getM() {
      java.lang.Object ref = m_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        m_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *detail  message if there is a error ,otherwise  null 
     * </pre>
     *
     * <code>string m = 2;</code>
     * @return The bytes for m.
     */
    public com.google.protobuf.ByteString
        getMBytes() {
      java.lang.Object ref = m_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        m_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *detail  message if there is a error ,otherwise  null 
     * </pre>
     *
     * <code>string m = 2;</code>
     * @param value The m to set.
     * @return This builder for chaining.
     */
    public Builder setM(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      m_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *detail  message if there is a error ,otherwise  null 
     * </pre>
     *
     * <code>string m = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearM() {
      
      m_ = getDefaultInstance().getM();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *detail  message if there is a error ,otherwise  null 
     * </pre>
     *
     * <code>string m = 2;</code>
     * @param value The bytes for m to set.
     * @return This builder for chaining.
     */
    public Builder setMBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      m_ = value;
      onChanged();
      return this;
    }

    private int se_ = 0;
    /**
     * <pre>
     * Serialization that support both java and c# , and code first , without IDL/proto file
     * </pre>
     *
     * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
     * @return The enum numeric value on the wire for se.
     */
    @java.lang.Override public int getSeValue() {
      return se_;
    }
    /**
     * <pre>
     * Serialization that support both java and c# , and code first , without IDL/proto file
     * </pre>
     *
     * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
     * @param value The enum numeric value on the wire for se to set.
     * @return This builder for chaining.
     */
    public Builder setSeValue(int value) {
      
      se_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialization that support both java and c# , and code first , without IDL/proto file
     * </pre>
     *
     * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
     * @return The se.
     */
    @java.lang.Override
    public com.bt.rpc.internal.SerEnum getSe() {
      @SuppressWarnings("deprecation")
      com.bt.rpc.internal.SerEnum result = com.bt.rpc.internal.SerEnum.valueOf(se_);
      return result == null ? com.bt.rpc.internal.SerEnum.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Serialization that support both java and c# , and code first , without IDL/proto file
     * </pre>
     *
     * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
     * @param value The se to set.
     * @return This builder for chaining.
     */
    public Builder setSe(com.bt.rpc.internal.SerEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      se_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialization that support both java and c# , and code first , without IDL/proto file
     * </pre>
     *
     * <code>.com.bt.rpc.internal.SerEnum se = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSe() {
      
      se_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string s = 4;</code>
     * @return Whether the s field is set.
     */
    @java.lang.Override
    public boolean hasS() {
      return pCase_ == 4;
    }
    /**
     * <code>string s = 4;</code>
     * @return The s.
     */
    @java.lang.Override
    public java.lang.String getS() {
      java.lang.Object ref = "";
      if (pCase_ == 4) {
        ref = p_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (pCase_ == 4) {
          p_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string s = 4;</code>
     * @return The bytes for s.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = "";
      if (pCase_ == 4) {
        ref = p_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (pCase_ == 4) {
          p_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string s = 4;</code>
     * @param value The s to set.
     * @return This builder for chaining.
     */
    public Builder setS(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  pCase_ = 4;
      p_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string s = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearS() {
      if (pCase_ == 4) {
        pCase_ = 0;
        p_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string s = 4;</code>
     * @param value The bytes for s to set.
     * @return This builder for chaining.
     */
    public Builder setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      pCase_ = 4;
      p_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bytes b = 5;</code>
     * @return Whether the b field is set.
     */
    public boolean hasB() {
      return pCase_ == 5;
    }
    /**
     * <code>bytes b = 5;</code>
     * @return The b.
     */
    public com.google.protobuf.ByteString getB() {
      if (pCase_ == 5) {
        return (com.google.protobuf.ByteString) p_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes b = 5;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  pCase_ = 5;
      p_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes b = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      if (pCase_ == 5) {
        pCase_ = 0;
        p_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bt.rpc.internal.OutputMessage)
  }

  // @@protoc_insertion_point(class_scope:com.bt.rpc.internal.OutputMessage)
  private static final com.bt.rpc.internal.OutputMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bt.rpc.internal.OutputMessage();
  }

  public static com.bt.rpc.internal.OutputMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutputMessage>
      PARSER = new com.google.protobuf.AbstractParser<OutputMessage>() {
    @java.lang.Override
    public OutputMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutputMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutputMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutputMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bt.rpc.internal.OutputMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

