//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: internal.proto
//
//package com.bt.rpc.internal;
//
///**
// * Protobuf enum {@code com.bt.rpc.internal.SerEnum}
// */
//public enum SerEnum {
//  /**
//   * <code>NONE = 0;</code>
//   */
//  NONE(0),
//  /**
//   * <code>JSON = 1;</code>
//   */
//  JSON(1),
//  /**
//   * <code>MSG_PACK = 2;</code>
//   */
//  MSG_PACK(2),
//  /**
//   * <code>HESSIAN = 3;</code>
//   */
//  HESSIAN(3),
//  /**
//   * <code>KRYO = 4;</code>
//   */
//  KRYO(4),
//  /**
//   * <code>PSR = 5;</code>
//   */
//  PSR(5),
//  UNRECOGNIZED(-1),
//  ;
//
//  public final int value;
//
//  private SerEnum(int value) {
//    this.value = value;
//  }
//
//  // @@protoc_insertion_point(enum_scope:com.bt.rpc.internal.SerEnum)
//}
//
