// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.bt.rpc.internal;

/**
 * Protobuf enum {@code com.bt.rpc.internal.SerEnum}
 */
public enum SerEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NONE = 0;</code>
   */
  NONE(0),
  /**
   * <code>JSON = 1;</code>
   */
  JSON(1),
  /**
   * <code>MSG_PACK = 2;</code>
   */
  MSG_PACK(2),
  /**
   * <code>HESSIAN = 3;</code>
   */
  HESSIAN(3),
  /**
   * <code>KRYO = 4;</code>
   */
  KRYO(4),
  /**
   * <code>PSR = 5;</code>
   */
  PSR(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NONE = 0;</code>
   */
  public static final int NONE_VALUE = 0;
  /**
   * <code>JSON = 1;</code>
   */
  public static final int JSON_VALUE = 1;
  /**
   * <code>MSG_PACK = 2;</code>
   */
  public static final int MSG_PACK_VALUE = 2;
  /**
   * <code>HESSIAN = 3;</code>
   */
  public static final int HESSIAN_VALUE = 3;
  /**
   * <code>KRYO = 4;</code>
   */
  public static final int KRYO_VALUE = 4;
  /**
   * <code>PSR = 5;</code>
   */
  public static final int PSR_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SerEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SerEnum forNumber(int value) {
    switch (value) {
      case 0: return NONE;
      case 1: return JSON;
      case 2: return MSG_PACK;
      case 3: return HESSIAN;
      case 4: return KRYO;
      case 5: return PSR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SerEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SerEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SerEnum>() {
          public SerEnum findValueByNumber(int number) {
            return SerEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bt.rpc.internal.Internal.getDescriptor().getEnumTypes().get(0);
  }

  private static final SerEnum[] VALUES = values();

  public static SerEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SerEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.bt.rpc.internal.SerEnum)
}

