apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
    revision: {{ .Chart.Version | replace "+" "_"  }}
  name: {{ .Values.appName  }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName  }}
  replicas: {{ .Values.deployment.replicas | default 1 }}
  template:
    metadata:
      annotations: 
        sidecar.istio.io/inject: "{{ .Values.deployment.istioInject | default true }}"
      labels:
        app: {{ .Values.appName }}
        component: java
    spec:
#     serviceAccountName: {{ .Values.deployment.serviceAccount | default "fabric8-service-account" }}
#      securityContext:
#        fsGroup: 1000
      containers:
        - name: {{ .Values.appName  }}
          image: {{ .Values.deployment.image.name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          command: ["/bin/bash","-c","{{ .Values.deployment.image.command  | default "./application" }}" ]
          env:
          - name: CLUSTER_NAME
            value: {{.Values.cd.cluster}}
          {{- range $key, $val := .Values.deployment.env }}
          - name: {{ $key }}
            value: {{ $val | quote}}
          {{- end }}
          {{- if .Values.secret }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}
          {{- end }}
          ports:
          {{- range $key, $val := .Values.service.ports }}
          - containerPort: {{ $val }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- $http_port := .Values.service.ports.http }}
          {{- with .Values.deployment.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $http_port }}
            failureThreshold: {{ .failure_threshold | default 15}}
            successThreshold: {{ .success_threshold | default 1 }}
            timeoutSeconds: {{ .timeout_seconds | default 1 }}
            initialDelaySeconds: {{ .initial_delay_seconds | default 10 }}
            periodSeconds: {{ .period_seconds | default 5 }}
          {{- end }}
          {{- with .Values.deployment.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $http_port }}
            failureThreshold: {{ .failure_threshold | default 15}}
            successThreshold: {{ .success_threshold | default 1 }}
            timeoutSeconds: {{ .timeout_seconds | default 1 }}
            initialDelaySeconds: {{ .initial_delay_seconds | default 10 }}
            periodSeconds: {{ .period_seconds | default 5 }}
          {{- end }}