apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName }}
    revision: {{ .Chart.Version | replace "+" "_" }}
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/api-gateway
  http:
    - match:
      - uri:
          prefix: "/{{ .Values.appName }}/"
      route:
      - destination:
          host: {{ .Values.appName  }}.{{ .Release.Namespace }}.svc.cluster.local
          subset: prod
          port:
            number: {{ .Values.service.port }}
        weight: {{ .Values.prod.weight }}
      - destination:
          host: {{ .Values.appName  }}.{{ .Release.Namespace }}.svc.cluster.local
          subset: canary
          port:
            number: {{ .Values.service.port }}
        weight: {{ .Values.canary.weight }}
      corsPolicy:
        allowOrigins:
        - prefix: "http://localhost"
        - exact: "https://{{ .Values.deployment.corsAllow }}"
        allowMethods:
        - POST
        - GET
        - OPTIONS
        allowCredentials: false
        allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - deadline
        - authorization
        - x-b3-traceid
        - x-forwarded-for
        - x-user-agent
        - x-grpc-web
        - custom-header-1
        exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
        maxAge: "1h"

{{- /*

      hosts: 可以有多个，取gw的交集，用*交给gw控制
        #    - {{ .Values.deployment.host | default "api.xx.com" }}
        gateways:
          #  - mesh # applies to all the sidecars in the mesh
          #    - {{ .Values.deployment.gateway | default "api-gateway" }}
          - match:
              - uri:
                  prefix: "/{{ .Values.appName }}/"

      #      rewrite:
      #        uri: /


*/}}