{{ if .Values.secret }}
{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision | quote }}
  name: {{ .Values.app_name }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
    {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{ end }}
{{ end }}
