apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName }}
    revision: {{ .Chart.Version | replace "+" "_"  }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.service.portName | default "http" }}
#    appProtocol: grpc-web
  selector:
    app: {{ .Values.appName  }}
