apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName }}
    revision: {{ .Chart.Version | replace "+" "_"  }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $val := .Values.service.ports }}
  - port: {{ $val }}
    targetPort: {{ $val }}
    name: {{ $key }} 
  {{- end }}
  selector:
    app: {{ .Values.appName  }}
