// source: internal.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.bt.rpc.internal.InputProto', null, global);
goog.exportSymbol('proto.com.bt.rpc.internal.OutputProto', null, global);
goog.exportSymbol('proto.com.bt.rpc.internal.OutputProto.DataCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bt.rpc.internal.InputProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bt.rpc.internal.InputProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.bt.rpc.internal.InputProto.displayName = 'proto.com.bt.rpc.internal.InputProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bt.rpc.internal.OutputProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.bt.rpc.internal.OutputProto.oneofGroups_);
};
goog.inherits(proto.com.bt.rpc.internal.OutputProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.bt.rpc.internal.OutputProto.displayName = 'proto.com.bt.rpc.internal.OutputProto';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bt.rpc.internal.InputProto.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bt.rpc.internal.InputProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bt.rpc.internal.InputProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.InputProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    utf8: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.bt.rpc.internal.InputProto}
 */
proto.com.bt.rpc.internal.InputProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.bt.rpc.internal.InputProto;
  return proto.com.bt.rpc.internal.InputProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.bt.rpc.internal.InputProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.bt.rpc.internal.InputProto}
 */
proto.com.bt.rpc.internal.InputProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtf8(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.InputProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.bt.rpc.internal.InputProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.bt.rpc.internal.InputProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.InputProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUtf8();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string utf8 = 2;
 * @return {string}
 */
proto.com.bt.rpc.internal.InputProto.prototype.getUtf8 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.InputProto} returns this
 */
proto.com.bt.rpc.internal.InputProto.prototype.setUtf8 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.bt.rpc.internal.OutputProto.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.com.bt.rpc.internal.OutputProto.DataCase = {
  DATA_NOT_SET: 0,
  UTF8: 3,
  BS: 4
};

/**
 * @return {proto.com.bt.rpc.internal.OutputProto.DataCase}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getDataCase = function() {
  return /** @type {proto.com.bt.rpc.internal.OutputProto.DataCase} */(jspb.Message.computeOneofCase(this, proto.com.bt.rpc.internal.OutputProto.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bt.rpc.internal.OutputProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bt.rpc.internal.OutputProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.OutputProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    c: jspb.Message.getFieldWithDefault(msg, 1, 0),
    m: jspb.Message.getFieldWithDefault(msg, 2, ""),
    utf8: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bs: msg.getBs_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.bt.rpc.internal.OutputProto}
 */
proto.com.bt.rpc.internal.OutputProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.bt.rpc.internal.OutputProto;
  return proto.com.bt.rpc.internal.OutputProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.bt.rpc.internal.OutputProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.bt.rpc.internal.OutputProto}
 */
proto.com.bt.rpc.internal.OutputProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setC(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setM(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtf8(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.bt.rpc.internal.OutputProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.bt.rpc.internal.OutputProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.OutputProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getC();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getM();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional int32 c = 1;
 * @return {number}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getC = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.setC = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string m = 2;
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getM = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.setM = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string utf8 = 3;
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getUtf8 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.setUtf8 = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.com.bt.rpc.internal.OutputProto.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.clearUtf8 = function() {
  return jspb.Message.setOneofField(this, 3, proto.com.bt.rpc.internal.OutputProto.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.hasUtf8 = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes bs = 4;
 * @return {!(string|Uint8Array)}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getBs = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes bs = 4;
 * This is a type-conversion wrapper around `getBs()`
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getBs_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBs()));
};


/**
 * optional bytes bs = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBs()`
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.getBs_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBs()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.setBs = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.com.bt.rpc.internal.OutputProto.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.bt.rpc.internal.OutputProto} returns this
 */
proto.com.bt.rpc.internal.OutputProto.prototype.clearBs = function() {
  return jspb.Message.setOneofField(this, 4, proto.com.bt.rpc.internal.OutputProto.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.bt.rpc.internal.OutputProto.prototype.hasBs = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.com.bt.rpc.internal);
