// source: internal.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.bt.rpc.internal.InputMessage', null, global);
goog.exportSymbol('proto.com.bt.rpc.internal.OutputMessage', null, global);
goog.exportSymbol('proto.com.bt.rpc.internal.OutputMessage.PCase', null, global);
goog.exportSymbol('proto.com.bt.rpc.internal.SerEnum', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bt.rpc.internal.InputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.bt.rpc.internal.InputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.bt.rpc.internal.InputMessage.displayName = 'proto.com.bt.rpc.internal.InputMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.bt.rpc.internal.OutputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_);
};
goog.inherits(proto.com.bt.rpc.internal.OutputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.bt.rpc.internal.OutputMessage.displayName = 'proto.com.bt.rpc.internal.OutputMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bt.rpc.internal.InputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bt.rpc.internal.InputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bt.rpc.internal.InputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.InputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    se: jspb.Message.getFieldWithDefault(msg, 1, 0),
    b: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.bt.rpc.internal.InputMessage}
 */
proto.com.bt.rpc.internal.InputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.bt.rpc.internal.InputMessage;
  return proto.com.bt.rpc.internal.InputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.bt.rpc.internal.InputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.bt.rpc.internal.InputMessage}
 */
proto.com.bt.rpc.internal.InputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.bt.rpc.internal.SerEnum} */ (reader.readEnum());
      msg.setSe(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setB(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.InputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.bt.rpc.internal.InputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.bt.rpc.internal.InputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.InputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSe();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getB();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional SerEnum se = 1;
 * @return {!proto.com.bt.rpc.internal.SerEnum}
 */
proto.com.bt.rpc.internal.InputMessage.prototype.getSe = function() {
  return /** @type {!proto.com.bt.rpc.internal.SerEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.com.bt.rpc.internal.SerEnum} value
 * @return {!proto.com.bt.rpc.internal.InputMessage} returns this
 */
proto.com.bt.rpc.internal.InputMessage.prototype.setSe = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string b = 2;
 * @return {string}
 */
proto.com.bt.rpc.internal.InputMessage.prototype.getB = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.InputMessage} returns this
 */
proto.com.bt.rpc.internal.InputMessage.prototype.setB = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.bt.rpc.internal.OutputMessage.oneofGroups_ = [[4,5]];

/**
 * @enum {number}
 */
proto.com.bt.rpc.internal.OutputMessage.PCase = {
  P_NOT_SET: 0,
  S: 4,
  B: 5
};

/**
 * @return {proto.com.bt.rpc.internal.OutputMessage.PCase}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getPCase = function() {
  return /** @type {proto.com.bt.rpc.internal.OutputMessage.PCase} */(jspb.Message.computeOneofCase(this, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.bt.rpc.internal.OutputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.bt.rpc.internal.OutputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.OutputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    c: jspb.Message.getFieldWithDefault(msg, 1, 0),
    m: jspb.Message.getFieldWithDefault(msg, 2, ""),
    se: jspb.Message.getFieldWithDefault(msg, 3, 0),
    s: jspb.Message.getFieldWithDefault(msg, 4, ""),
    b: msg.getB_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.bt.rpc.internal.OutputMessage}
 */
proto.com.bt.rpc.internal.OutputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.bt.rpc.internal.OutputMessage;
  return proto.com.bt.rpc.internal.OutputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.bt.rpc.internal.OutputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.bt.rpc.internal.OutputMessage}
 */
proto.com.bt.rpc.internal.OutputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setC(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setM(value);
      break;
    case 3:
      var value = /** @type {!proto.com.bt.rpc.internal.SerEnum} */ (reader.readEnum());
      msg.setSe(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setS(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setB(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.bt.rpc.internal.OutputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.bt.rpc.internal.OutputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.bt.rpc.internal.OutputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getC();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getM();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSe();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional int32 c = 1;
 * @return {number}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getC = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.setC = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string m = 2;
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getM = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.setM = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional SerEnum se = 3;
 * @return {!proto.com.bt.rpc.internal.SerEnum}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getSe = function() {
  return /** @type {!proto.com.bt.rpc.internal.SerEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.com.bt.rpc.internal.SerEnum} value
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.setSe = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string s = 4;
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getS = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.setS = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.clearS = function() {
  return jspb.Message.setOneofField(this, 4, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.hasS = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bytes b = 5;
 * @return {!(string|Uint8Array)}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getB = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes b = 5;
 * This is a type-conversion wrapper around `getB()`
 * @return {string}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getB_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getB()));
};


/**
 * optional bytes b = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getB()`
 * @return {!Uint8Array}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.getB_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getB()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.setB = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.com.bt.rpc.internal.OutputMessage} returns this
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.clearB = function() {
  return jspb.Message.setOneofField(this, 5, proto.com.bt.rpc.internal.OutputMessage.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.bt.rpc.internal.OutputMessage.prototype.hasB = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.com.bt.rpc.internal.SerEnum = {
  NONE: 0,
  JSON: 1,
  MSG_PACK: 2,
  HESSIAN: 3,
  KRYO: 4,
  PSR: 5
};

goog.object.extend(exports, proto.com.bt.rpc.internal);
