app_name: demo-java-server-jvm

service:
  type: ClusterIP
  ports: 
    grpc: 50051

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi

platform:
  cd:
    cluster: local-test

deployment:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    name: "docker-local.jfrog.io/demo-java-server:latest"
    # -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    command: "java ${JAVA_OPT} -jar app.jar"
  env:
    APP_ENV: TEST
    LOG_LEVEL: warn


