appName: demo-java-client

service:
  type: ClusterIP
  port: 50051
  appProtocol: grpc-web

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

cd:
  cluster: local-test


deployment:
  corsAllow: course.botaoyx.com
  image:
    pullPolicy: IfNotPresent
    name: "jcr.botaoyx.com/img/example/demo-java-client"
  env:
    APP_ENV: TEST
    LOG_LEVEL: warn

prod:
  replicas: 2
  weight: 100
  tag: 83


canary:
  replicas: 0
  weight: 0
  tag: ""
